# 네임스페이스 생성
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
# 홈페이지 파드용 서비스 생성
apiVersion: v1
kind: Service
metadata:
  name: service-example
  namespace: logging
spec:
  selector:
    app: web-example
  ports:
  - name: http
    protocol: TCP
    nodePort: 30000
    port: 8088
    targetPort: 8080
  type: NodePort
---
# 홈페이지 파드 생성
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-example
  namespace: logging
spec:
  selector:
    matchLabels:
      app: web-example
  replicas: 3
  template:
    metadata:
      labels:
        app: web-example
    spec:
      containers:
      - name: web-example
        image: minjun5876/home:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-pull-secret  